### ISSUE TITLE
Broken HTML layout in thread

### ISSUE THREAD

**Issue by riking** [Xkeeper0/jul#40]
Seen on: https://jul.rustedlogic.net/thread.php?id=18227&page=3

The first three posts on the page have no wrapping `div`. Also, there's no identifying class name on the post body - ideally, the `div` would have `class=post`.

```
<table width="100%">...title...</table>
<table width="100%">...pages...</table>
<div style="position:relative">
	</div>
<table class="table" cellspacing="0">post</table>
<table class="table" cellspacing="0">post</table>
<table class="table" cellspacing="0">post</table>
<div style="position:relative"><table class="table" cellspacing="0">post</table></div>
<div style="position:relative"><table class="table" cellspacing="0">post</table></div>
<div style="position:relative"><table class="table" cellspacing="0">post</table></div>
```

**Comment by Xkeeper0** [comment]
That looks like something from post-processing, i.e. not the actual source of the page (devtools?)

Part of the problem is that the code was changed at one point to move from "enclose entire thread in one table" to "each post is its own table" (to prevent posts from "table breaking" if they had too wide of an image or something).

There's a spurious `<tr>` getting added here: https://github.com/Xkeeper0/jul/blob/a6a22e7ea9b30c9b9a83b9566cb0fdf768e601a2/thread.php#L372

The "position: relative" `<div>`s are added here, which may not be getting added to "custom sidebars": https://github.com/Xkeeper0/jul/blob/a6a22e7ea9b30c9b9a83b9566cb0fdf768e601a2/tlayouts/regular.php#L240

(I'm not actually sure why the `position-relative` is there, to be honest)
